- hosts: docker
  become: true
  roles:
    - docker

- hosts: swarm_manager
  become: true
  vars:
    swarm_info:
  roles:
    - swarm_manager
  gather_facts: no
  tasks: []

- hosts: swarm_worker
  become: true
  vars:
    swarm_info:
  roles:
  - swarm_worker
