- name: install pip
apt:
  name: python3-pip
- name: pip install docker
pip:
  name: docker
- name: Init a new swarm 
docker_swarm:
  state: present
- name: Inspect swarm
docker_swarm:
  state: inspect
register: swarm_info
