- name: install pip
  apt:
    name: python3-pip
- name: pip install docker
  pip:
    name: docker
- name: Add node
  docker_swarm:
    state: join
    advertise_addr: vm-1
    join_token: "{{ hostvars[groups['swarm_init'][0]]['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: sfia2-instance:2377
- name: Add node
  docker_swarm:
    state: join
    advertise_addr: vm-2
    join_token: "{{ hostvars[groups['swarm_init'][0]]['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: sfia2-instance:2377
