- name: install pip
  apt:
    name: python3-pip
- name: pip install docker
  pip:
    name: docker
- name: Add node
  docker_swarm:
    state: join
    advertise_addr: worker-vm-1
    join_token: "{{ hostvars[groups['swarm_manager'][0]]['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: manager-vm-1:2377
- name: Add node
  docker_swarm:
    state: join
    advertise_addr: worker-vm-2
    join_token: "{{ hostvars[groups['swarm_manager'][0]]['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: manager-vm-1:2377
